// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebScrapingApp.Data;

#nullable disable

namespace WebScrapingApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230815191805_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebScrapingApp.Models.SearchResult", b =>
                {
                    b.Property<int>("SearchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SearchId"));

                    b.Property<string>("SearchTerm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SearchUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SelectedSearchEngine")
                        .HasColumnType("int");

                    b.HasKey("SearchId");

                    b.ToTable("SearchResults");
                });

            modelBuilder.Entity("WebScrapingApp.Models.SearchResultItem", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PositionId"));

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("SearchId")
                        .HasColumnType("int");

                    b.Property<int>("SearchResultSearchId")
                        .HasColumnType("int");

                    b.HasKey("PositionId");

                    b.HasIndex("SearchResultSearchId");

                    b.ToTable("SearchResultItem");
                });

            modelBuilder.Entity("WebScrapingApp.Models.SearchResultItem", b =>
                {
                    b.HasOne("WebScrapingApp.Models.SearchResult", "SearchResult")
                        .WithMany("SearchResults")
                        .HasForeignKey("SearchResultSearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SearchResult");
                });

            modelBuilder.Entity("WebScrapingApp.Models.SearchResult", b =>
                {
                    b.Navigation("SearchResults");
                });
#pragma warning restore 612, 618
        }
    }
}
